version: '2.4'

services:
  gametest:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.140
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./:/opt/gametest:delegated
      - ./package.json:/opt/gametest/package.json
      - ./package-lock.json:/opt/gametest/package-lock.json
      - notused:/opt/gametest/node_modules
    healthcheck:
      disable: true

volumes:
  notused:
